DefaultContentLanguage = "en"
author = "AWS User Group India Community"
baseURL = "https://blog.awsug.in/"
copyright = "2020"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "AWS User Group India Blog"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "register"
name = "Register for Community Day India"
url = "https://communityday.awsug.in/"
weight = 40
[params]
description = "AWS User Group India's blog"
facebook = "https://www.facebook.com/awsugindia"
github = "https://github.com/awsug"
logo = "/images/ug-logo-for-profile-pic-dark.png"
mainSections = ["post"]
twitter = "https://www.twitter.com/awsugindia"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
